### ISSUE TITLE
скрипт выполняется без ошибок, но таблицы не создаются

### ISSUE THREAD

**Issue by 2nikitinalexandr2** [undermuz/junior-php-contest#1]
Подскажите в чем у меня ошибка, после выполнения  команды `php composer.phar bootstrap` таблицы в базе не создаются но и ошибок нет

1) Версия ОС Ubuntu 20.04.4 LTS
2) Версия PHP PHP 8.0.21
3) Версия Composer composer Composer - Dependency Manager for PHP - version 2.3.10
4) Способ установки composer: локально

**Comment by undermuz** [comment]
@2nikitinalexandr2 
ответил в твоем репозитории
